version: '3.8'

services:
  node-red:
    image: nodered/node-red:latest
    container_name: email-node-red
    restart: unless-stopped
    ports:
      - "1880:1880"
    volumes:
      - ./data/node-red:/data
      - ./config/node-red:/config
    environment:
      - TZ=Europe/Warsaw
      - NODE_RED_ENABLE_PROJECTS=true
    networks:
      - email-net

  ollama:
    image: ollama/ollama:latest
    container_name: email-ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ./data/ollama:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
    networks:
      - email-net

  prometheus:
    image: prom/prometheus:latest
    container_name: email-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus:/etc/prometheus
      - ./data/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    networks:
      - email-net

  grafana:
    image: grafana/grafana:latest
    container_name: email-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./config/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./config/grafana/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    networks:
      - email-net

  redis:
    image: redis:alpine
    container_name: email-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    networks:
      - email-net

networks:
  email-net:
    driver: bridge

volumes:
  node-red-data:
  ollama-data:
  prometheus-data:
  grafana-data:
  redis-data: