version: '3'

services:
  taskinity-email:
    image: python:3.9-slim
    container_name: taskinity-email-mock
    volumes:
      - ../../../..:/app
    working_dir: /app/examples/email_processing
    environment:
      - MOCK_EMAILS=true
      - PYTHONPATH=/app
      - IMAP_SERVER=mockserver
      - IMAP_PORT=1080
      - IMAP_USERNAME=user@taskinity.org
      - IMAP_PASSWORD=password123
      - SMTP_SERVER=mockserver
      - SMTP_PORT=1025
      - SMTP_USERNAME=user@taskinity.org
      - SMTP_PASSWORD=password123
      - FROM_EMAIL=user@taskinity.org
    command: >
      bash -c "pip install -r requirements.txt &&
               python flow.py"
    depends_on:
      - mockserver
    networks:
      - taskinity-network

  mockserver:
    image: mailhog/mailhog
    container_name: taskinity-mockserver
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web UI port
    networks:
      - taskinity-network
    
  # Web interface for viewing emails
  webui:
    image: nginx:alpine
    container_name: taskinity-email-webui
    volumes:
      - ./webui:/usr/share/nginx/html
    ports:
      - "8080:80"
    networks:
      - taskinity-network

networks:
  taskinity-network:
    driver: bridge
