# Konfiguracja ładowana z pliku .env
email:
  imap:
    host: ${EMAIL_IMAP_HOST}
    port: ${EMAIL_IMAP_PORT}
    username: ${EMAIL_IMAP_USERNAME}
    password: ${EMAIL_IMAP_PASSWORD}
    folder: ${EMAIL_IMAP_FOLDER}
    check_interval: ${EMAIL_IMAP_CHECK_INTERVAL}  # sekundy
  smtp:
    host: ${EMAIL_SMTP_HOST}
    port: ${EMAIL_SMTP_PORT}
    username: ${EMAIL_SMTP_USERNAME}
    password: ${EMAIL_SMTP_PASSWORD}

attachments:
  save_path: ${ATTACHMENTS_PATH}

monitoring:
  enabled: true
  log_level: ${LOG_LEVEL}
  dashboard_port: ${DASHBOARD_PORT}
  metrics_enabled: ${METRICS_ENABLED}
